### задача 1

In [3]:
import numpy as np

In [6]:
a = np.array([[1,6],
              [2,8],
              [3,11],
              [3,10],
              [1,7]])

In [11]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### задача 2

In [13]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### задача 3

In [24]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1])
a_centered_sp

8.0

In [29]:
a_centered_sp / (a.shape[0] - 1)

2.0

### задача 4

In [35]:
a = a.T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [36]:
np.cov(a.T)


array([[1. , 2. ],
       [2. , 4.3]])